services:
  - type: web
    name: foodcheck
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GNEWS_API_KEY
        sync: false
